opensearch-pipeline:
  source:
    opensearch:
      hosts: ["http://localhost:9200/"]
      max_retries: 3
      username: "admin"
      password: "admin"
      connection:
        insecure: true
        cert: "cert"
        socket_timeout:
        connection_timeout:
      aws:
        region: "us-east-1"
        sts_role_arn: "arn:aws:iam::278936200144:role/aos-role"
      indices:
        include:
          - "customdata"
        exclude:
          - ""
      scheduling:
        rate: P90DT3H4M
        job_count: 1
        start_time: 2023-05-15T18:00:00Z
      query:
        fields: ["play_name : Henry VI Part 1"]
      search_options:
        batch_size: 1000
        expand_wildcards: "open"
        sorting:
          - sort_key: "line_id"
            order: "asc"
  sink:
    - stdout:
